apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<user>:<password>@<cluster>.mongodb.net/?appName=<app>"
  JWT_SECRET: "<random-hex-string>"
  ADMIN_TASK_TOKEN: "<random-token>"
  SEED_DEMO_PASSWORD: "<password-for-scripts-seedDemoAccount.js>"
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""
